### PR TITLE
Fix nodeagent unit tests

### LINKED ISSUE #238: Fix nodeagent unit tests
Recently some nodeagent unit tests have started failing, but this only happens every once in a while. Currently we haven't found a way to replicate this except running the tests multiple times.

### PR DESCRIPTION
**Pull request by javier-op**
Fixes #238

### CODE REVIEW

File: cmd/nodeagent/nodeagentmanager.go [hunk 1]
```diff
@@ -129,7 +129,7 @@ func (n *NodeAgentManager) HeartbeatTimeChecker() {
 		}
 		gsd.Mutex.RUnlock()
 		if state != gotHeartbeat {
-			n.markGameServerUnhealthy(gameServerName, gameServerNamespace, state)
+			go n.markGameServerUnhealthy(gameServerName, gameServerNamespace, state)
```
Comment (dgkanatsios) [inline cmd/nodeagent/nodeagentmanager.go:132]: any special reason we're running this in a goroutine?

File: cmd/nodeagent/nodeagentmanager_test.go [hunk 2]
```diff
@@ -90,7 +90,7 @@ var _ = Describe("nodeagent tests", func() {
 		_ = json.Unmarshal(resBody, &hbr)
 		Expect(hbr.Operation).To(Equal(GameOperationContinue))
 	})
-	It("should transition properly from standingBy to Active", func() {
+	It("should transition properly from standingBy to Active", FlakeAttempts(3), func() {
```
Comment (dgkanatsios) [inline cmd/nodeagent/nodeagentmanager_test.go:93]: can we make "3" a const for the entire file?

**Review by dgkanatsios — APPROVED** [review]
