### PR TITLE
Attempt to fix the unit test bug

### LINKED ISSUE #118: fix setting GameServerBuild to Unhealthy
Currently, the code that sets that GameServerBuild to Unhealthy fetches the current CrashesCount number, adds 1 to it and then persists it to the CR.status. This can create problem when crashes come too rapidly and the cached GameServerBuild has not been updated. We should add a sync.map and track changes there.

### PR DESCRIPTION
**Pull request by dgkanatsios**
Fixes #118

### CODE REVIEW

File: cmd/e2e/utilities.go [hunk 1]
```diff
@@ -191,6 +191,13 @@ func verifyGameServerBuild(ctx context.Context, buildID, buildName string, state
 		return fmt.Errorf("expected %d crashes, got %d", state.crashesCount, gameServerBuild.Status.CrashesCount)
 	}
 
+	// 5 is the default, we should parameterize that
+	if gameServerBuild.Status.CrashesCount >= 5 && gameServerBuild.Status.Health != "Unhealthy" {
+		return fmt.Errorf("expected %s health, got %s", "Unhealthy", gameServerBuild.Status.Health)
```
Comment (khaines) [inline cmd/e2e/utilities.go:196]:
```suggestion
		return fmt.Errorf("expected %s status, got %s", "Unhealthy", gameServerBuild.Status.Health)
```

File: cmd/e2e/utilities.go [hunk 2]
```diff
@@ -191,6 +191,13 @@ func verifyGameServerBuild(ctx context.Context, buildID, buildName string, state
...
+	} else if gameServerBuild.Status.CrashesCount < 5 && gameServerBuild.Status.Health != "Healthy" {
+		return fmt.Errorf("expected %s health, got %s", "Healthy", gameServerBuild.Status.Health)
```
Comment (khaines) [inline cmd/e2e/utilities.go:198]:
```suggestion
		return fmt.Errorf("expected %s status, got %s", "Healthy", gameServerBuild.Status.Health)
```

**Review by khaines — APPROVED** [review]
LGTM, one minor suggestion on wording
